#playlist for now playing

#playlist for now playing

MUSIC_LIST = [
    "Now playing : 回忆观影券 - In K & 王忻辰  | t.me/my_thingsuwu",
    "Now playing : Chikatto Chika Chikkatsu - Lizz Robinett | t.me/my_thingsuwu",
    "Now playing : ZITTI E BUONI - Måneskin  | t.me/my_thingsuwu",
    "Now playing : Let's go - BTS | t.me/my_thingsuwu",
    "Now playing : Winter Bear - V | t.me/my_thingsuwu",
    "Now playing : Late Night Melancholy - Rude Boy | t.me/my_thingsuwu",
    "Now Playing :  Super Idol - Ukutela  | t.me/my_thingsuwu",
    "Now Playing : Dear Maria as an Anime Intro : Foxchase | t.me/my_thingsuwu",
    "Now Playing : Monsieur Periné Feat. Vicente García - Nuestra Canción | t.me/my_thingsuwu",
    "Now Playing : コウを追いかけて | t.me/my_thingsuwu",
    "Now Playing : Suicide Year (Lo-fi Remix) - ABSURD & Weedmane | t.me/my_thingsuwu",
    "Now Playing : One Last Time(抖音热播版) - 王亚鹏 | t.me/my_thingsuwu",
    "Now Playing : Tokyo - Leat'eq | t.me/my_thingsuwu",
    "Now Playing : Ture Feelings - Agent K | t.me/my_thingsuwu",
    "Now Playing : Sukide - Oxbelt Redfur | t.me/my_thingsuwu",
    "Now Playing : Com ou Sem Mim - Gustavo Mioto | t.me/my_thingsuwu",
    "Now Playing : 第一优先 - 次林 | t.me/my_thingsuwu",
    "Now Playing : Morena - Mariana Nolasco part. Vitor Kley | t.me/my_thingsuwu",
    "Now Playing : Mariana Nolasco - Te Assumi Pro Brasil | t.me/my_thingsuwu",
    "Now Playing : Lei Da Vida - Sabrina Lopes | t.me/my_thingsuwu",
    "Now Playing : Hadal Ahbek - Issam Alnajjar | t.me/my_thingsuwu",
    "Now Playing : 夜に駆ける - YOASOBI | t.me/my_thingsuwu",
    "Now Playing : たぶん - YOASOBI | t.me/my_thingsuwu",]

ENGLISH_QUOTES = [
    "Now Playing : I WANNA BE YOUR SLAVE - Måneskin | t.me/my_thingsuwu",
    "Now Playing : you're mine - Kina | t.me/my_thingsuwu",
    "Now Playing : Good 4 you - Olivia Rodriguez | t.me/my_thingsuwu",
    "Now Playing : Paralyzed - NF | t.me/my_thingsuwu",
    "Now Playing : Runaway - AURORA | t.me/my_thingsuwu",
    "Now Playing : Escape Velocity - Zombi | t.me/my_thingsuwu",
    "Now Playing : Softcore - The Neighbourhood | t.me/my_thingsuwu",
    "Now Playing : Heat Waves - Glass Animals | t.me/my_thingsuwu",
    "Now Playing : Beggin' - Måneskin | t.me/my_thingsuwu",
    "Now Playing : Friday - Fishi | t.me/my_thingsuwu",
    "Now Playing : Lucky - Lucky Twice | t.me/my_thingsuwu",
    "Now Playing : Middle of the Night - Elley Duhé | t.me/my_thingsuwu",
    "Now Playing : What If - Johnny Orlando & Mackenzie Ziegler | t.me/my_thingsuwu",
    "Now Playing : This One Is for You - Yung City | t.me/my_thingsuwu",
    "Now Playing : Evil On The Inside - Masked Wolf Feat. iiiConic | t.me/my_thingsuwu",
    "Now Playing : Astronaut In The Ocean : Masked Wolf | t.me/my_thingsuwu",
    "Now Playing : Normal No More - TYSM | t.me/my_thingsuwu",
    "Now Playing : Stan - Eminem Feat. Dido | t.me/my_thingsuwu",
    "Now Playing : Believe Me - Navos | t.me/my_thingsuwu",
    "Now Playing : Love Story - Taylor Swift | t.me/my_thingsuwu",
    "Now Playing : All the Things You Said - JPlus | t.me/my_thingsuwu",
    "Now Playing : Made of you - Chymes | t.me/my_thingsuwu",
    "Now Playing : Industry E.T. - Felax | t.me/my_thingsuwu",
    "Now Playing : Coastline - Hollow Coves | t.me/my_thingsuwu",
    "Now Playing : After Dark - Mr.Kitty | t.me/my_thingsuwu",
    "Now Playing : Idfc - Blackbear | t.me/my_thingsuwu", 
    "Now Playing : Wasted - Juice WRLD Feat. Lil Uzi Vert | t.me/my_thingsuwu",
    "Now Playing : Dead To Me - Whales, Fraxo & Lox Chatterbox | t.me/my_thingsuwu",
    "Now Playing : Early Morning Dreams - Kadebostany | t.me/my_thingsuwu",
    "Now Playing : My Ordinary Life - The Living Tombstone | t.me/my_thingsuwu",
    "Now Playing : Camel By Camel  - Sandy Marton | t.me/my_thingsuwu",
    "Now Playing : Pope Is A Rockstar - SALES | t.me/my_thingsuwu",
    "Now Playing : Fireflies - Owl City | t.me/my_thingsuwu",
    "Now Playing : Death Bed (Coffee For Your Head) - Ebmusic | t.me/my_thingsuwu",
    "Now Playing : Umbrella - Hard Lights | t.me/my_thingsuwu",
    "Now Playing : Naked Soul - Last Heroes Feat. Liel Kolet | t.me/my_thingsuwu",
    "Now Playing : overwhelmed - Royal & the Serpent | t.me/my_thingsuwu",
    "Now Playing : As the World Caves In - Sarah Cothran | t.me/my_thingsuwu",
    "Now Playing : I’ll Keep You Safe - Vluestar | t.me/my_thingsuwu",
    "Now Playing : House of Memories - Panic at the Disco | t.me/my_thingsuwu", 
    # seperate 
    "Now playing : 回忆观影券 - In K & 王忻辰  | t.me/my_thingsuwu",
    "Now playing : Chikatto Chika Chikkatsu - Lizz Robinett | t.me/my_thingsuwu",
    "Now playing : ZITTI E BUONI - Måneskin  | t.me/my_thingsuwu",
    "Now playing : Let's go - BTS | t.me/my_thingsuwu",
    "Now playing : Winter Bear - V | t.me/my_thingsuwu",
    "Now playing : Late Night Melancholy - Rude Boy | t.me/my_thingsuwu",
    "Now Playing :  Super Idol - Ukutela  | t.me/my_thingsuwu",
    "Now Playing : Dear Maria as an Anime Intro : Foxchase | t.me/my_thingsuwu",
    "Now Playing : Monsieur Periné Feat. Vicente García - Nuestra Canción | t.me/my_thingsuwu",
    "Now Playing : コウを追いかけて | t.me/my_thingsuwu",
    "Now Playing : Suicide Year (Lo-fi Remix) - ABSURD & Weedmane | t.me/my_thingsuwu",
    "Now Playing : One Last Time(抖音热播版) - 王亚鹏 | t.me/my_thingsuwu",
    "Now Playing : Tokyo - Leat'eq | t.me/my_thingsuwu",
    "Now Playing : Ture Feelings - Agent K | t.me/my_thingsuwu",
    "Now Playing : Sukide - Oxbelt Redfur | t.me/my_thingsuwu",
    "Now Playing : Com ou Sem Mim - Gustavo Mioto | t.me/my_thingsuwu",
    "Now Playing : 第一优先 - 次林 | t.me/my_thingsuwu",
    "Now Playing : Morena - Mariana Nolasco part. Vitor Kley | t.me/my_thingsuwu",
    "Now Playing : Mariana Nolasco - Te Assumi Pro Brasil | t.me/my_thingsuwu",
    "Now Playing : Lei Da Vida - Sabrina Lopes | t.me/my_thingsuwu",
    "Now Playing : Hadal Ahbek - Issam Alnajjar | t.me/my_thingsuwu",
    "Now Playing : 夜に駆ける - YOASOBI | t.me/my_thingsuwu",
    "Now Playing : たぶん - YOASOBI | t.me/my_thingsuwu" ]
